# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute store result score @s aj.id run scoreboard players add aj.last_id aj.id 1
# Data Manager: Initalize per-entity storage
function animated_java:global/gu/get_entity_uuid_string
data modify storage animated_java:temp args.uuid set from storage animated_java:gu out
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
function animated_java:global/data_manager/create_entry with storage animated_java:temp args
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Read
function animated_java:global/data_manager/read with storage animated_java:temp args
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.root_uuid set from storage animated_java:gu out
data modify storage animated_java:temp entry.data.blueprint_id set value "aj:worldradio_jukebox"
data modify storage animated_java:temp entry.data.rig_hash set value "1cfed9fadee27c14316c62ef684318fdff5a10a06f98a03131ac8f77d2f00223"
tp @s ~ ~ ~ ~ ~
summon minecraft:interaction ^-0.25 ^1.125 ^0.75 { Tags:["","aj.global.bone.buttons.child","aj.global.bone.buttons.child.interaction","aj.global.bone.buttons.decendant","aj.global.bone.buttons.decendant.interaction","aj.global.bone.buttons.tree","aj.global.bone.jukebox.decendant","aj.global.bone.jukebox.decendant.interaction","aj.global.bone.jukebox.tree","aj.global.entity","aj.global.interaction","aj.global.node","aj.global.node.interaction","aj.new","aj.worldradio_jukebox.bone.buttons.child","aj.worldradio_jukebox.bone.buttons.child.interaction","aj.worldradio_jukebox.bone.buttons.decendant","aj.worldradio_jukebox.bone.buttons.decendant.interaction","aj.worldradio_jukebox.bone.buttons.tree","aj.worldradio_jukebox.bone.jukebox.decendant","aj.worldradio_jukebox.bone.jukebox.decendant.interaction","aj.worldradio_jukebox.bone.jukebox.tree","aj.worldradio_jukebox.entity","aj.worldradio_jukebox.interaction","aj.worldradio_jukebox.interaction.interaction","aj.worldradio_jukebox.node","aj.worldradio_jukebox.node.interaction"], response: false, width: 0.1875f, height: 0.1875f, }
execute as @n[ type=minecraft:interaction, tag=aj.worldradio_jukebox.interaction.interaction, tag=aj.new, distance=..2 ] run function aj:worldradio_jukebox/zzz/summon/as_interaction/interaction
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.interaction set from storage animated_java:gu out
data modify storage animated_java:temp entry.data.interactions.interaction.uuid set from storage animated_java:gu out
summon minecraft:interaction ^0.25 ^1.125 ^0.75 { Tags:["","aj.global.bone.buttons.child","aj.global.bone.buttons.child.interaction","aj.global.bone.buttons.decendant","aj.global.bone.buttons.decendant.interaction","aj.global.bone.buttons.tree","aj.global.bone.jukebox.decendant","aj.global.bone.jukebox.decendant.interaction","aj.global.bone.jukebox.tree","aj.global.entity","aj.global.interaction","aj.global.node","aj.global.node.interaction2","aj.new","aj.worldradio_jukebox.bone.buttons.child","aj.worldradio_jukebox.bone.buttons.child.interaction","aj.worldradio_jukebox.bone.buttons.decendant","aj.worldradio_jukebox.bone.buttons.decendant.interaction","aj.worldradio_jukebox.bone.buttons.tree","aj.worldradio_jukebox.bone.jukebox.decendant","aj.worldradio_jukebox.bone.jukebox.decendant.interaction","aj.worldradio_jukebox.bone.jukebox.tree","aj.worldradio_jukebox.entity","aj.worldradio_jukebox.interaction","aj.worldradio_jukebox.interaction.interaction2","aj.worldradio_jukebox.node","aj.worldradio_jukebox.node.interaction2"], response: false, width: 0.1875f, height: 0.1875f, }
execute as @n[ type=minecraft:interaction, tag=aj.worldradio_jukebox.interaction.interaction2, tag=aj.new, distance=..2 ] run function aj:worldradio_jukebox/zzz/summon/as_interaction/interaction2
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.interaction2 set from storage animated_java:gu out
data modify storage animated_java:temp entry.data.interactions.interaction2.uuid set from storage animated_java:gu out
summon minecraft:interaction ^0.7187 ^1.125 ^0.75 { Tags:["","aj.global.bone.buttons.child","aj.global.bone.buttons.child.interaction","aj.global.bone.buttons.decendant","aj.global.bone.buttons.decendant.interaction","aj.global.bone.buttons.tree","aj.global.bone.jukebox.decendant","aj.global.bone.jukebox.decendant.interaction","aj.global.bone.jukebox.tree","aj.global.entity","aj.global.interaction","aj.global.node","aj.global.node.interaction3","aj.new","aj.worldradio_jukebox.bone.buttons.child","aj.worldradio_jukebox.bone.buttons.child.interaction","aj.worldradio_jukebox.bone.buttons.decendant","aj.worldradio_jukebox.bone.buttons.decendant.interaction","aj.worldradio_jukebox.bone.buttons.tree","aj.worldradio_jukebox.bone.jukebox.decendant","aj.worldradio_jukebox.bone.jukebox.decendant.interaction","aj.worldradio_jukebox.bone.jukebox.tree","aj.worldradio_jukebox.entity","aj.worldradio_jukebox.interaction","aj.worldradio_jukebox.interaction.interaction3","aj.worldradio_jukebox.node","aj.worldradio_jukebox.node.interaction3"], response: false, width: 0.25f, height: 0.1875f, }
execute as @n[ type=minecraft:interaction, tag=aj.worldradio_jukebox.interaction.interaction3, tag=aj.new, distance=..3 ] run function aj:worldradio_jukebox/zzz/summon/as_interaction/interaction3
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.interaction3 set from storage animated_java:gu out
data modify storage animated_java:temp entry.data.interactions.interaction3.uuid set from storage animated_java:gu out
summon minecraft:interaction ^-0.7188 ^1.125 ^0.75 { Tags:["","aj.global.bone.buttons.child","aj.global.bone.buttons.child.interaction","aj.global.bone.buttons.decendant","aj.global.bone.buttons.decendant.interaction","aj.global.bone.buttons.tree","aj.global.bone.jukebox.decendant","aj.global.bone.jukebox.decendant.interaction","aj.global.bone.jukebox.tree","aj.global.entity","aj.global.interaction","aj.global.node","aj.global.node.interaction4","aj.new","aj.worldradio_jukebox.bone.buttons.child","aj.worldradio_jukebox.bone.buttons.child.interaction","aj.worldradio_jukebox.bone.buttons.decendant","aj.worldradio_jukebox.bone.buttons.decendant.interaction","aj.worldradio_jukebox.bone.buttons.tree","aj.worldradio_jukebox.bone.jukebox.decendant","aj.worldradio_jukebox.bone.jukebox.decendant.interaction","aj.worldradio_jukebox.bone.jukebox.tree","aj.worldradio_jukebox.entity","aj.worldradio_jukebox.interaction","aj.worldradio_jukebox.interaction.interaction4","aj.worldradio_jukebox.node","aj.worldradio_jukebox.node.interaction4"], response: false, width: 0.25f, height: 0.1875f, }
execute as @n[ type=minecraft:interaction, tag=aj.worldradio_jukebox.interaction.interaction4, tag=aj.new, distance=..3 ] run function aj:worldradio_jukebox/zzz/summon/as_interaction/interaction4
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.interaction4 set from storage animated_java:gu out
data modify storage animated_java:temp entry.data.interactions.interaction4.uuid set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.worldradio_jukebox.node.b3] run function aj:worldradio_jukebox/zzz/summon/as_node/b3
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.b3 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.worldradio_jukebox.node.b2] run function aj:worldradio_jukebox/zzz/summon/as_node/b2
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.b2 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.worldradio_jukebox.node.b4] run function aj:worldradio_jukebox/zzz/summon/as_node/b4
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.b4 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.worldradio_jukebox.node.b1] run function aj:worldradio_jukebox/zzz/summon/as_node/b1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.b1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.worldradio_jukebox.node.desk] run function aj:worldradio_jukebox/zzz/summon/as_node/desk
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.desk set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.worldradio_jukebox.node.bone1] run function aj:worldradio_jukebox/zzz/summon/as_node/bone1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.worldradio_jukebox.node.bone2] run function aj:worldradio_jukebox/zzz/summon/as_node/bone2
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone2 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.worldradio_jukebox.node.bone3] run function aj:worldradio_jukebox/zzz/summon/as_node/bone3
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone3 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.worldradio_jukebox.node.bone4] run function aj:worldradio_jukebox/zzz/summon/as_node/bone4
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone4 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.worldradio_jukebox.node.open_terminator] run function aj:worldradio_jukebox/zzz/summon/as_node/open_terminator
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.open_terminator set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.worldradio_jukebox.node.w] run function aj:worldradio_jukebox/zzz/summon/as_node/w
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.w set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.worldradio_jukebox.node.o] run function aj:worldradio_jukebox/zzz/summon/as_node/o
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.o set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.worldradio_jukebox.node.r] run function aj:worldradio_jukebox/zzz/summon/as_node/r
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.r set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.worldradio_jukebox.node.l] run function aj:worldradio_jukebox/zzz/summon/as_node/l
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.l set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.worldradio_jukebox.node.d] run function aj:worldradio_jukebox/zzz/summon/as_node/d
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.d set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.worldradio_jukebox.node.r1] run function aj:worldradio_jukebox/zzz/summon/as_node/r1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.r1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.worldradio_jukebox.node.a] run function aj:worldradio_jukebox/zzz/summon/as_node/a
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.a set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.worldradio_jukebox.node.d1] run function aj:worldradio_jukebox/zzz/summon/as_node/d1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.d1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.worldradio_jukebox.node.i] run function aj:worldradio_jukebox/zzz/summon/as_node/i
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.i set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.worldradio_jukebox.node.o1] run function aj:worldradio_jukebox/zzz/summon/as_node/o1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.o1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.worldradio_jukebox.node.close_terminator] run function aj:worldradio_jukebox/zzz/summon/as_node/close_terminator
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.close_terminator set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.worldradio_jukebox.node.worldradio_title] run function aj:worldradio_jukebox/zzz/summon/as_node/worldradio_title
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.worldradio_title set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.worldradio_jukebox.node.pin] run function aj:worldradio_jukebox/zzz/summon/as_node/pin
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.pin set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.worldradio_jukebox.node.music_disc] run function aj:worldradio_jukebox/zzz/summon/as_node/music_disc
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.music_disc set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.worldradio_jukebox.node.music_disc_collection] run function aj:worldradio_jukebox/zzz/summon/as_node/music_disc_collection
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.music_disc_collection set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.worldradio_jukebox.node.window] run function aj:worldradio_jukebox/zzz/summon/as_node/window
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.window set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.worldradio_jukebox.node.jukebox] run function aj:worldradio_jukebox/zzz/summon/as_node/jukebox
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.jukebox set from storage animated_java:gu out
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
function aj:worldradio_jukebox/zzz/set_default_pose
execute if data storage animated_java:temp args.variant run function aj:worldradio_jukebox/zzz/summon/variant_arg/process with storage animated_java:temp args
execute if score #success aj.i matches 0 run return fail
execute if data storage animated_java:temp args.animation run function aj:worldradio_jukebox/zzz/summon/animation_arg/process with storage animated_java:temp args
execute if score #success aj.i matches 0 run return fail
execute on passengers run rotate @s ~ ~
data modify entity @s teleport_duration set value 1
execute on passengers run data modify entity @s teleport_duration set value 1
function aj:worldradio_jukebox/zzz/summon/zzz/0 with storage animated_java:temp entry.data.interactions
tag @s remove aj.new
execute on passengers run tag @s remove aj.new