# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.interactions.$(name).uuid
function aj:worldradio_jukebox/zzz/as_interaction/execute_as_uuid with storage animated_java:temp args