# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(antenna) { transformation: [-1f,0f,0f,0.0071f,0f,1f,0f,0.4063f,0f,0f,-1f,-0.3f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(speaker_right) { transformation: [-1f,0f,0f,0.4759f,0f,1f,0f,0.2813f,0f,0f,-1f,0.2625f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(speaker_left) { transformation: [-1f,0f,0f,-0.4616f,0f,1f,0f,0.2813f,0f,0f,-1f,0.2625f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(text_display) { transformation: [0.25f,0f,0f,0f,0f,0.25f,0f,0.6563f,0f,0f,0.1f,0.3f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(boombox) { transformation: [-1f,0f,0f,0f,0f,1f,0f,0f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }