# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$kill $(antenna)
$kill $(speaker_right)
$kill $(speaker_left)
$kill $(text_display)
$kill $(boombox)