# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$function aj:worldradio_jukebox/zzz/summon/zzz/1 $(interaction)
$function aj:worldradio_jukebox/zzz/summon/zzz/2 $(interaction2)
$function aj:worldradio_jukebox/zzz/summon/zzz/3 $(interaction3)
$function aj:worldradio_jukebox/zzz/summon/zzz/4 $(interaction4)