# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute at @s run particle minecraft:note ~ ~2 ~ 0.25 0.25 0.25 0.1 2 force @a[distance=..15]