# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.interactions.interaction.uuid
function aj:worldradio_jukebox/zzz/as_all_interactions/execute_as_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.interactions.interaction2.uuid
function aj:worldradio_jukebox/zzz/as_all_interactions/execute_as_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.interactions.interaction3.uuid
function aj:worldradio_jukebox/zzz/as_all_interactions/execute_as_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.interactions.interaction4.uuid
function aj:worldradio_jukebox/zzz/as_all_interactions/execute_as_uuid with storage animated_java:temp args