# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if entity @s[tag=aj.worldradio_boombox.animation.playing.playing] run function aj:worldradio_boombox/animations/playing/zzz/on_tick
execute on passengers run rotate @s ~ ~