# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage aj:worldradio_jukebox rig_hash set value 'db012c11de2ce9d59308463c6d11bc662fd9a491a2f25886b32aad8d6859ee85'
scoreboard objectives add aj.playing.frame dummy
scoreboard objectives add aj.switch.frame dummy
scoreboard objectives add aj.next.frame dummy
scoreboard objectives add aj.previous.frame dummy
scoreboard objectives add aj.play.frame dummy
scoreboard objectives add aj.stop.frame dummy
scoreboard objectives add aj.start.frame dummy
scoreboard objectives add aj.stopping.frame dummy