# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove aj.worldradio_jukebox.animation.playing.playing
tag @s remove aj.worldradio_jukebox.animation.switch.playing
tag @s remove aj.worldradio_jukebox.animation.next.playing
tag @s remove aj.worldradio_jukebox.animation.previous.playing
tag @s remove aj.worldradio_jukebox.animation.play.playing
tag @s remove aj.worldradio_jukebox.animation.stop.playing
tag @s remove aj.worldradio_jukebox.animation.start.playing
tag @s remove aj.worldradio_jukebox.animation.stopping.playing