# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if entity @s[tag=aj.worldradio_jukebox.animation.playing.playing] run function aj:worldradio_jukebox/animations/playing/zzz/on_tick
execute if entity @s[tag=aj.worldradio_jukebox.animation.switch.playing] run function aj:worldradio_jukebox/animations/switch/zzz/on_tick
execute if entity @s[tag=aj.worldradio_jukebox.animation.next.playing] run function aj:worldradio_jukebox/animations/next/zzz/on_tick
execute if entity @s[tag=aj.worldradio_jukebox.animation.previous.playing] run function aj:worldradio_jukebox/animations/previous/zzz/on_tick
execute if entity @s[tag=aj.worldradio_jukebox.animation.play.playing] run function aj:worldradio_jukebox/animations/play/zzz/on_tick
execute if entity @s[tag=aj.worldradio_jukebox.animation.stop.playing] run function aj:worldradio_jukebox/animations/stop/zzz/on_tick
execute if entity @s[tag=aj.worldradio_jukebox.animation.start.playing] run function aj:worldradio_jukebox/animations/start/zzz/on_tick
execute if entity @s[tag=aj.worldradio_jukebox.animation.stopping.playing] run function aj:worldradio_jukebox/animations/stopping/zzz/on_tick
function aj:worldradio_jukebox/root/on_tick/transform_floating_entities
execute on passengers run rotate @s ~ ~