# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function aj:worldradio_jukebox/root/on_tick/select_interaction_interaction with storage animated_java:temp entry.data.interactions.interaction
function aj:worldradio_jukebox/root/on_tick/select_interaction_interaction2 with storage animated_java:temp entry.data.interactions.interaction2
function aj:worldradio_jukebox/root/on_tick/select_interaction_interaction3 with storage animated_java:temp entry.data.interactions.interaction3
function aj:worldradio_jukebox/root/on_tick/select_interaction_interaction4 with storage animated_java:temp entry.data.interactions.interaction4