# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:temp args merge from storage animated_java:temp entry.data.interactions.interaction
function aj:worldradio_jukebox/zzz/at_all_interactions/execute_at_transform with storage animated_java:temp args
data modify storage animated_java:temp args merge from storage animated_java:temp entry.data.interactions.interaction2
function aj:worldradio_jukebox/zzz/at_all_interactions/execute_at_transform with storage animated_java:temp args
data modify storage animated_java:temp args merge from storage animated_java:temp entry.data.interactions.interaction3
function aj:worldradio_jukebox/zzz/at_all_interactions/execute_at_transform with storage animated_java:temp args
data modify storage animated_java:temp args merge from storage animated_java:temp entry.data.interactions.interaction4
function aj:worldradio_jukebox/zzz/at_all_interactions/execute_at_transform with storage animated_java:temp args