# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(b3) {transformation: [-1f,0f,0f,-0.1875f,0f,1f,0f,1.0625f,0f,0f,-1f,0.8125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(b2) {transformation: [-1f,0f,0f,0.3125f,0f,1f,0f,1.0625f,0f,0f,-1f,0.8125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(b4) {transformation: [-1f,0f,0f,-0.625f,0f,1f,0f,1.0625f,0f,0f,-1f,0.8125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(b1) {transformation: [-1f,0f,0f,0.625f,0f,1f,0f,1.0625f,0f,0f,-1f,0.8125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(desk) {transformation: [-1.3433f,0f,0f,0.625f,0f,1.3433f,0f,1.0625f,0f,0f,-1.3433f,0.8125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone1) {transformation: [-1f,0f,0f,0.5625f,0f,1f,0f,2.25f,0f,0f,-1f,-0.25f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone2) {transformation: [-1f,0f,0f,0.5625f,0f,1f,0f,2.25f,0f,0f,-1f,-0.0781f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone3) {transformation: [-1f,0f,0f,0.5469f,0f,1f,0f,1.9375f,0f,0f,-1f,-0.0781f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone4) {transformation: [-1f,0f,0f,0.2578f,0f,1f,0f,2.25f,0f,0f,-1f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(open_terminator) {transformation: [-1f,0f,0f,0f,0f,1f,0f,2.4375f,0f,0f,-1f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(w) {transformation: [-1f,0f,0f,0f,0f,1f,0f,2.4375f,0f,0f,-1f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(o) {transformation: [-1f,0f,0f,0f,0f,1f,0f,2.4375f,0f,0f,-1f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r) {transformation: [-1f,0f,0f,0f,0f,1f,0f,2.4375f,0f,0f,-1f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l) {transformation: [-1f,0f,0f,0f,0f,1f,0f,2.4375f,0f,0f,-1f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(d) {transformation: [-1f,0f,0f,0f,0f,1f,0f,2.4375f,0f,0f,-1f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r1) {transformation: [-1f,0f,0f,0f,0f,1f,0f,2.4375f,0f,0f,-1f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(a) {transformation: [-1f,0f,0f,0f,0f,1f,0f,2.4375f,0f,0f,-1f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(d1) {transformation: [-1f,0f,0f,0f,0f,1f,0f,2.4375f,0f,0f,-1f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(i) {transformation: [-1f,0f,0f,0f,0f,1f,0f,2.4375f,0f,0f,-1f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(o1) {transformation: [-1f,0f,0f,0f,0f,1f,0f,2.4375f,0f,0f,-1f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(close_terminator) {transformation: [-1f,0f,0f,0f,0f,1f,0f,2.4375f,0f,0f,-1f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(worldradio_title) {transformation: [-1f,0f,0f,0f,0f,1f,0f,2.4375f,0f,0f,-1f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(pin) {transformation: [-0.8121f,-0.1305f,0.5687f,0.625f,-0.1069f,0.9914f,0.0749f,1.4531f,-0.5736f,0f,-0.8192f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(music_disc) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.4063f,0f,0f,-1f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(music_disc_collection) {transformation: [-1f,0f,0f,-1f,0f,1f,0f,2.5625f,0f,0f,-1f,-0.25f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(window) {transformation: [-2.2083f,0f,0f,0.0625f,0f,2.2083f,0f,-0.3125f,0f,0f,-2.2083f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(jukebox) {transformation: [-2.076f,0f,0f,0.0625f,0f,2.076f,0f,0f,0f,0f,-2.076f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"interactions":{"interaction":{"px":-0.25,"py":1.125,"pz":0.75,"ry":0,"rx":0},"interaction2":{"px":0.25,"py":1.125,"pz":0.75,"ry":0,"rx":0},"interaction3":{"px":0.7187,"py":1.125,"pz":0.75,"ry":0,"rx":0},"interaction4":{"px":-0.7188,"py":1.125,"pz":0.75,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args