# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone1) {transformation: [-1f,0f,0f,0.5625f,0f,1f,0f,2.25f,0f,0f,-1.2f,-0.2308f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone2) {transformation: [-1f,0f,0f,0.5625f,0f,1f,0f,2.25f,0f,0f,-1f,-0.03f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone3) {transformation: [-0.8845f,-0.5878f,0f,0.5499f,-0.6426f,0.809f,0f,1.9283f,0f,0f,-1f,-0.03f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone4) {transformation: [-0.809f,-0.5878f,0f,0.1148f,-0.5878f,0.809f,0f,1.9985f,0f,0f,-1f,-0.0168f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}