# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone1) {transformation: [-1f,0f,0f,0.5625f,0f,1f,0f,2.25f,0f,0f,-1.312f,-0.22f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone2) {transformation: [-1f,0f,0f,0.5625f,0f,1f,0f,2.25f,0f,0f,-1f,-0.0031f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone3) {transformation: [-0.6701f,-0.809f,0f,0.5533f,-0.9223f,0.5878f,0f,1.9249f,0f,0f,-1f,-0.0031f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone4) {transformation: [-0.5878f,-0.809f,0f,0.1108f,-0.809f,0.5878f,0f,1.8474f,0f,0f,-1f,0.0088f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}