# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone1) {transformation: [-1f,0f,0f,0.5625f,0f,1f,0f,2.25f,0f,0f,-1.4f,-0.2115f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone2) {transformation: [-1f,0f,0f,0.5625f,0f,1f,0f,2.25f,0f,0f,-1f,0.018f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone3) {transformation: [-0.3667f,-0.9511f,0f,0.5577f,-1.1286f,0.309f,0f,1.9226f,0f,0f,-1f,0.018f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone4) {transformation: [-0.309f,-0.9511f,0f,0.1578f,-0.9511f,0.309f,0f,1.7031f,0f,0f,-1f,0.0288f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}