# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone1) {transformation: [-0.5f,0f,1.9919f,0.3054f,0f,1f,0f,2.25f,-0.866f,0f,-1.15f,-0.2734f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone2) {transformation: [-0.5f,0f,0.866f,-0.0058f,0f,1f,0f,2.25f,-0.866f,0f,-0.5f,-0.0937f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone3) {transformation: [0f,-0.5f,0.866f,-0.0058f,-0.7f,0f,0f,1.9219f,0f,-0.866f,-0.5f,-0.0937f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone4) {transformation: [0f,-0.5f,0.866f,-0.1621f,-2.8f,0f,0f,1.7734f,0f,-0.866f,-0.5f,-0.3644f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(music_disc) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.7188f,0f,0f,-1f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}