# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone1) {transformation: [-1f,0f,0f,0.5625f,0f,1f,0f,2.25f,0f,0f,-1.52f,-0.2f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone2) {transformation: [-1f,0f,0f,0.5625f,0f,1f,0f,2.25f,0f,0f,-1f,0.0469f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone3) {transformation: [0f,-1f,0f,0.5625f,-1.2333f,0f,0f,1.9219f,0f,0f,-1f,0.0469f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone4) {transformation: [0f,-1f,0f,0.25f,-1f,0f,0f,1.5766f,0f,0f,-1f,0.0563f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}