# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone1) {transformation: [-1f,0f,0f,0.5625f,0f,1f,0f,2.25f,0f,0f,-1.104f,-0.24f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone2) {transformation: [-1f,0f,0f,0.5625f,0f,1f,0f,2.25f,0f,0f,-1f,-0.0531f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone3) {transformation: [-0.9954f,-0.309f,0f,0.5476f,-0.3234f,0.9511f,0f,1.9327f,0f,0f,-1f,-0.0531f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone4) {transformation: [-0.9511f,-0.309f,0f,0.1655f,-0.309f,0.9511f,0f,2.1371f,0f,0f,-1f,-0.0388f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}