# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone1) {transformation: [-1f,0f,0f,0.5625f,0f,1f,0f,2.25f,0f,0f,-1f,-0.25f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone2) {transformation: [-1f,0f,0f,0.5625f,0f,1f,0f,2.25f,0f,0f,-1f,-0.0781f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone3) {transformation: [-1f,0f,0f,0.5469f,0f,1f,0f,1.9375f,0f,0f,-1f,-0.0781f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone4) {transformation: [-1f,0f,0f,0.2578f,0f,1f,0f,2.25f,0f,0f,-1f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}