# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute store result score @s aj.id run scoreboard players add aj.last_id aj.id 1
# Data Manager: Initalize per-entity storage
function animated_java:global/gu/get_entity_uuid_string
data modify storage animated_java:temp args.uuid set from storage animated_java:gu out
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
function animated_java:global/data_manager/create_entry with storage animated_java:temp args
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Read
function animated_java:global/data_manager/read with storage animated_java:temp args
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.root_uuid set from storage animated_java:gu out
data modify storage animated_java:temp entry.data.blueprint_id set value "aj:worldradio_boombox"
data modify storage animated_java:temp entry.data.rig_hash set value "7ad27ee2c1fe44dd8b0a4299d6084436e64aaab1def5165e54cdedcd0021e035"
tp @s ~ ~ ~ ~ ~
execute on passengers if entity @s[tag=aj.worldradio_boombox.node.antenna] run function aj:worldradio_boombox/zzz/summon/as_node/antenna
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.antenna set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.worldradio_boombox.node.speaker_right] run function aj:worldradio_boombox/zzz/summon/as_node/speaker_right
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.speaker_right set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.worldradio_boombox.node.speaker_left] run function aj:worldradio_boombox/zzz/summon/as_node/speaker_left
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.speaker_left set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.worldradio_boombox.node.text_display] run function aj:worldradio_boombox/zzz/summon/as_node/text_display
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.text_display set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.worldradio_boombox.node.boombox] run function aj:worldradio_boombox/zzz/summon/as_node/boombox
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.boombox set from storage animated_java:gu out
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
function aj:worldradio_boombox/zzz/set_default_pose
execute if data storage animated_java:temp args.variant run function aj:worldradio_boombox/zzz/summon/zzz/variant_arg/no_variants_warning
execute if score #success aj.i matches 0 run return fail
execute if data storage animated_java:temp args.animation run function aj:worldradio_boombox/zzz/summon/animation_arg/process with storage animated_java:temp args
execute if score #success aj.i matches 0 run return fail
execute on passengers run rotate @s ~ ~
data modify entity @s teleport_duration set value 1
execute on passengers run data modify entity @s teleport_duration set value 1
execute on passengers if entity @s[tag=aj.worldradio_boombox.node.text_display] run function aj:worldradio_boombox/zzz/summon/on_summon/text_display_text_display
tag @s remove aj.new
execute on passengers run tag @s remove aj.new