# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage aj:worldradio_boombox rig_hash set value '6682e1ea1493b00f919585f1ef38d86e5e9570f0eecc53ecb114d9a57e704cde'
scoreboard objectives add aj.playing.frame dummy