# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage aj:worldradio_boombox rig_hash set value '7ad27ee2c1fe44dd8b0a4299d6084436e64aaab1def5165e54cdedcd0021e035'
scoreboard objectives add aj.playing.frame dummy