# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(antenna) {transformation: [-1.0625f,-0.2847f,0f,-0.0699f,-0.2847f,1.0625f,0f,0.5664f,0f,0f,-1.1f,-0.33f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(speaker_right) {transformation: [-1.1916f,-0.2101f,0f,0.4618f,-0.2101f,1.1916f,0f,0.5206f,0f,0f,-1.21f,0.2888f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(speaker_left) {transformation: [-1.1916f,-0.2101f,0f,-0.5538f,-0.2101f,1.1916f,0f,0.3415f,0f,0f,-1.21f,0.2888f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(text_display) {transformation: [0.2708f,-0.0478f,0f,-0.1254f,0.0478f,0.2708f,0f,0.8359f,0f,0f,0.11f,0.33f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(boombox) {transformation: [-1.0833f,-0.191f,0f,0f,-0.191f,1.0833f,0f,0.125f,0f,0f,-1.1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
execute unless entity @s[tag=aj.transforms_only] at @s run function aj:worldradio_boombox/animations/playing/zzz/frames/15_root_function